### PR TITLE
Add ability to pass extra options to duplicity

### PR DESCRIPTION
**Pull request by adamcrews**

### CODE REVIEW

**Comment by adamcrews** [comment]
It looks like the checks that failed on travis are due to ruby 1.8.7 silliness.  I vote to drop ruby 1.8.7 support.

**Comment by tohuwabohu** [comment]
I've removed Ruby 1.8.7 from the test matrix. Can you please pull from master? The tests should pass now.

**Comment by adamcrews** [comment]
I rebased from master and tests are passing now.  Thanks!

**Comment by tohuwabohu** [comment]
Thank you for your contribution. I've released version 3.4.0 to the forge.

**Pull request merged**
