### PR TITLE
Added parameter for TEMP_DIR

### PR DESCRIPTION
**Pull request by Samgarr**
Thanks for merging.

### CODE REVIEW

**Comment by tohuwabohu** [comment]
Not 100% what's going on with this PR, it shows many changes. Can you please resolve the conflicts and try again?

**Comment by Samgarr** [comment]
Rebased and conflicts resolved.

**Comment by tohuwabohu** [comment]
Many thanks!

**Comment by tohuwabohu** [comment]
Released as 4.10.0 to the forge.

**Comment by Samgarr** [comment]
Great, thank you.

**Pull request merged**
