### PR TITLE
Add niceness option to profile

### PR DESCRIPTION
**Pull request by ElliottLandsborough**
I wanted to be able to set my backups to be low priority - this seemed like the easiest way.

### CODE REVIEW

**Comment by tohuwabohu** [comment]
Looks good. Can you have a look at the failing build, please?

**Comment by ElliottLandsborough** [comment]
The build errors aren't to do with my code - see here: https://travis-ci.org/tohuwabohu/puppet-duplicity/builds/176518418

The latest version of json_pure is not compatible with ruby 1.9.3 which is causing travis to freak out.

**Comment by tohuwabohu** [comment]
Fair enough, I'll have to have a look at the build then. Nevertheless, thanks for the contribution!

**Comment by tohuwabohu** [comment]
I've released version 4.1.0 to the forge

**Pull request merged**
